### ISSUE TITLE
Save model and train on multiple instances

### ISSUE THREAD

**Issue by yochem** [prosysscience/RL-Job-Shop-Scheduling#22]
Dear maintainers,

Thank you for this research and making the code available to the public.

I'm currently using this model for my thesis and was wondering two things;

1. How can the trained model be used later on? Are parameters saved somewhere?
2. Is it possible to train on multiple instances? Right now this is in the config: `'instance_path': 'instances/ta41'`, which seems to me like it only trains on that one. Is this true?

Thank you in advance for answering the questions. Have a nice day!

**Comment by ingambe** [comment]
Hello,

Happy to hear you find our work useful :)

1) In the current version of the code, we don't save the hyperparameter as we haven't explored pre-training approaches. Mainly because the instances we tested our approach on were generated randomly, so pre-training was not yelling good results.
It shouldn't be hard to implement however using RLLib API (`export_model` function if I remember correctly): https://docs.ray.io/en/master/rllib-package-ref.html?highlight=export#module-ray.rllib.policy

2) Yes the environment takes only one instance as an argument. The easiest way to implement multi-instances IMO would be to use an environment wrapper that loads multiple environments with the different instances and let him select the desired environment depending on some conditions.

Thank you,
Have a nice day too :)

**Comment by yochem** [comment]
Thank you!
